/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Meta informações referente à API requisitada.
type ResponseErrorMeta struct {
	// Número total de registros no resultado
	TotalRecords int32 `json:"totalRecords"`
	// Número total de páginas no resultado
	TotalPages int32 `json:"totalPages"`
}
