/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ResponseMetricsListData struct {
	// URL ou URI do endpoint
	Endpoint string `json:"endpoint"`
	// Data e hora que as métricas foram requisitadas.
	RequestTime time.Time `json:"requestTime"`

	Availability *AvailabilityMetrics `json:"availability"`

	Invocations *InvocationMetrics `json:"invocations"`

	AverageResponse *AverageMetrics `json:"averageResponse"`

	AverageTps *AverageTpsMetrics `json:"averageTps"`

	PeakTps *PeakTpsMetrics `json:"peakTps"`

	Errors *ErrorMetrics `json:"errors"`

	Rejections *RejectionMetrics `json:"rejections"`
}
