/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AvailabilityMetricsUptime struct {
	// Taxa de disponibilidade (considerando todos os serviços ativos ao mesmo tempo).
	GeneralUptimeRate string `json:"generalUptimeRate"`
	// Taxa de disponibilidade do endpoint.
	UptimeRate string `json:"uptimeRate"`
}
