/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AvailabilityMetricsDowntime struct {
	// Quantidade de segundos de downtime (considerando qualquer api em downtime).
	GeneralDowntime int32 `json:"generalDowntime"`
	// Quantidade de segundos de indisponibilidade agendada.
	ScheduledOutage int32 `json:"scheduledOutage"`
	// Quantidade de segundos de indisponibilidade do endpoint.
	PartialDowntime int32 `json:"partialDowntime"`
}
