/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Links struct {
	// URL da página atualmente requisitada
	Self string `json:"self,omitempty"`
	// URL da primeira página de registros
	First string `json:"first,omitempty"`
	// URL da página anterior de registros
	Prev string `json:"prev,omitempty"`
	// URL da próxima página de registros
	Next string `json:"next,omitempty"`
	// URL da última página de registros
	Last string `json:"last,omitempty"`
}
