/*
 * APIs Admin do Open Finance Brasil
 *
 * As API's administrativas são recursos que podem ser consumidos apenas pelo diretório para avaliação e controle da qualidade dos serviços fornecidos pelas instituições financeiras
 *
 * API version: 2.0.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

// Meta informações referente à API requisitada.
type ResponseErrorMetaSingleMeta struct {
	// Data e hora da consulta, conforme especificação RFC-3339, formato UTC.
	RequestDateTime time.Time `json:"requestDateTime"`
}
